services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGX_USER}
      POSTGRES_PASSWORD: ${PGX_PASS}
      POSTGRES_DB: ${PGX_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  redis:
    image: redis:alpine
    command:
      ["redis-server", "--requirepass", "${RDB_PASS}", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  postgres_data:
  redis_data: {}

networks:
  backend:
